project:
  type: website

website:
  title: "Maitner Lab"
  site-url: https://MaitnerLab.github.io/
  #favicon: images/openscapes_hex.png  
  
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/), with theme from [vetiver](https://github.com/rstudio/vetiver.rstudio.com)"
    left: "&copy; CC-By NASA Openscapes"
 
  navbar:
   # logo: images/openscapes_hex.png
    #href: https://openscapes.org
    right:
     - text: "Home"
       href: index.html
    #- text: "About"                      
    #  menu:
    #    - text: "About"
    #      href: about.qmd
    #    - text: "Slides"
    #      href: about.qmd#slides          
    #    - text: "Events Archive"
    #      href: events.qmd
    #- text: "Mentors"
    #  href: mentors.qmd
    #- text: "Champions"
    #  href: champions.qmd
    #- text: "Cookbook"
    #  href: cookbook-navbar-page.qmd
    #- text: "News & Events"
    #  href: news.qmd  
    - icon: github
      href: https://github.com/MaitnerLab
    #- icon: mastodon
    #  href: https://fosstodon.org/@openscapes

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left
