---
layout: splash
permalink: /software/
---


# R packages

### BIEN

[BIEN](https://cran.r-project.org/package=BIEN) is an R package that allows users to easily download various types of plant data (e.g. occurrence records, range maps, trait data)

### TNRS

The Taxonomic Name Resolution Service ([TNRS](https://cran.r-project.org/package=BIEN)) cleans and standardizes plant scientific names.

### <a href = "https://github.com/EnquistLab/RNSR">NSR</a>

The Native Species Resolver (NSR) categorizes plant occurrence records as native or non-native, and provides details on how this decision was made.

### <a href = "https://cran.r-project.org/package=GNRS">GNRS</a>

The Geographic Name Resolution Service (GNRS) cleans and standardizes political division names based on geonames.org and GADM standards.


### <a href = "https://cran.r-project.org/package=occCite">occCite</a>

occCite downloads species occurrence data while maintaining citation information to ensure that proper credit is maintained.

# Web Applications

### <a href = "https://ecoinformatica.net/GCMcompareR.html">GCMcompareR</a>

GCMcompareR is designed to compare general circulation models (GCMs) and different climate change scenarios to provide full, documented exploration of the possible alternative futures from within the range of projections in CMIP5 climate models.

# Code from publications
*Coming soon!*
